"""Initial migration

Revision ID: eaf5ec389b3c
Revises: 
Create Date: 2023-10-29 22:18:16.963908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eaf5ec389b3c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=32), nullable=False),
    sa.Column('image_file', sa.String(length=20), nullable=False),
    sa.Column('notif_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('username')
    )
    op.create_table('followers',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('follows_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['follows_id'], ['users.uid'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.uid'], )
    )
    op.create_table('posts',
    sa.Column('pid', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('media', sa.String(length=32), nullable=True),
    sa.Column('date_posted', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('pid')
    )
    op.create_table('comments',
    sa.Column('cid', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date_posted', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.pid'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('cid')
    )
    op.create_table('likes',
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.pid'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.uid'], )
    )
    op.create_table('notifs',
    sa.Column('nid', sa.Integer(), nullable=False),
    sa.Column('msg', sa.Text(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('for_uid', sa.Integer(), nullable=False),
    sa.Column('author', sa.String(length=20), nullable=False),
    sa.Column('date_posted', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['for_uid'], ['users.uid'], ),
    sa.ForeignKeyConstraint(['post_id'], ['posts.pid'], ),
    sa.PrimaryKeyConstraint('nid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notifs')
    op.drop_table('likes')
    op.drop_table('comments')
    op.drop_table('posts')
    op.drop_table('followers')
    op.drop_table('users')
    # ### end Alembic commands ###
